// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8OTnGDB1LvrXtV2Xg1FxyhfAkqw-P7U',
    appId: '1:466078534071:web:3e9ce99c2fc65300c4c032',
    messagingSenderId: '466078534071',
    projectId: 'fluttergram-eb856',
    authDomain: 'fluttergram-eb856.firebaseapp.com',
    storageBucket: 'fluttergram-eb856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA05NWJ090as-aXToDzkJsQm7poq-gZgcI',
    appId: '1:466078534071:android:85b2b35325ecfc96c4c032',
    messagingSenderId: '466078534071',
    projectId: 'fluttergram-eb856',
    storageBucket: 'fluttergram-eb856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2hNLQVWvs3GxPWgfeodLMJt3azCqfPI',
    appId: '1:466078534071:ios:640a036c3fd77f23c4c032',
    messagingSenderId: '466078534071',
    projectId: 'fluttergram-eb856',
    storageBucket: 'fluttergram-eb856.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2hNLQVWvs3GxPWgfeodLMJt3azCqfPI',
    appId: '1:466078534071:ios:7681ca7b1aca4911c4c032',
    messagingSenderId: '466078534071',
    projectId: 'fluttergram-eb856',
    storageBucket: 'fluttergram-eb856.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
